function figure4()
% Create public-facing Figure 4 panels.
%
% Inputs:
%   1. Thresholded No > Yes statistical map
%   2. Joined ROI/questionnaire CSV produced by roi_statistics.m
%
% Edit USER SETTINGS, then run:
%   figure4

%% USER SETTINGS
spmDir = 'C:\path\to\spm';

noGreaterThanYesMap = [ ...
    'D:\path\to\secondlevel_public\' ...
    'Figure4_No_gt_Yes\thresholded_p001_display.nii'];

joinedDataFile = [ ...
    'D:\path\to\roi_output\statistics\' ...
    'roi_questionnaire_joined.csv'];

outputDir = 'D:\path\to\figure_output\Figure4';

addpath(spmDir);
if isempty(which('spm'))
    error('SPM was not found. Check spmDir.');
end

if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

canonicalT1 = fullfile(spmDir, 'canonical', 'avg152T1.nii');

% Brain-map panels
create_brain_panel( ...
    canonicalT1, ...
    noGreaterThanYesMap, ...
    [48 21 44], ...
    'Right dlPFC: Emotion No > Yes', ...
    fullfile(outputDir, 'Figure4A_dlPFC_No_gt_Yes.png'));

create_brain_panel( ...
    canonicalT1, ...
    noGreaterThanYesMap, ...
    [60 -58 35], ...
    'Right TPJ: Emotion No > Yes', ...
    fullfile(outputDir, 'Figure4C_TPJ_No_gt_Yes.png'));

% Correlation panels
T = readtable(joinedDataFile, 'VariableNamingRule', 'preserve');

make_scatter( ...
    T.TAS20_total_z, ...
    T.Right_dlPFC_mean, ...
    'TAS-20 total score (z)', ...
    'Right dlPFC mean contrast value', ...
    fullfile(outputDir, 'Figure4B_dlPFC_TAS20.png'));

make_scatter( ...
    T.SC_Collectivism_z, ...
    T.Right_dlPFC_mean, ...
    '\DeltaSC (z)', ...
    'Right dlPFC mean contrast value', ...
    fullfile(outputDir, 'Figure4B_dlPFC_SC.png'));

make_scatter( ...
    T.TAS20_total_z, ...
    T.Right_TPJ_mean, ...
    'TAS-20 total score (z)', ...
    'Right TPJ mean contrast value', ...
    fullfile(outputDir, 'Figure4D_TPJ_TAS20.png'));

make_scatter( ...
    T.SC_Collectivism_z, ...
    T.Right_TPJ_mean, ...
    '\DeltaSC (z)', ...
    'Right TPJ mean contrast value', ...
    fullfile(outputDir, 'Figure4D_TPJ_SC.png'));

end


function create_brain_panel(backgroundImage, statisticalMap, coordinate, ...
    panelTitle, outputFile)

fig = figure('Color', 'w', 'Visible', 'off', ...
    'Position', [100 100 1200 800]);

spm_orthviews('Reset');
spm_orthviews('Image', backgroundImage, [0.05 0.08 0.90 0.84]);
spm_orthviews('AddColouredImage', 1, statisticalMap, [1 0 0]);
spm_orthviews('Reposition', coordinate);
spm_orthviews('Redraw');

annotation(fig, 'textbox', [0.05 0.93 0.90 0.05], ...
    'String', panelTitle, ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

exportgraphics(fig, outputFile, 'Resolution', 300);
close(fig);
end


function make_scatter(x, y, xLabelText, yLabelText, outputFile)

x = double(x(:));
y = double(y(:));
valid = isfinite(x) & isfinite(y);

[r, p] = corr(x(valid), y(valid), 'Type', 'Pearson');

fig = figure('Color', 'w', 'Visible', 'off', ...
    'Position', [100 100 600 500]);

scatter(x(valid), y(valid), 60, 'filled');
hold on;

coefficient = polyfit(x(valid), y(valid), 1);
xLine = linspace(min(x(valid)), max(x(valid)), 100);
plot(xLine, polyval(coefficient, xLine), 'LineWidth', 1.5);

grid on;
xlabel(xLabelText);
ylabel(yLabelText);
title(sprintf('r = %.3f, p = %.4f, N = %d', ...
    r, p, sum(valid)));

exportgraphics(fig, outputFile, 'Resolution', 300);
close(fig);
end
